### ISSUE TITLE
Access blocked: This app’s request is invalid

### ISSUE THREAD

**Issue by jpomykala** [vedantnn71/bud#14]
![Screenshot 2022-12-06 at 17 51 49](https://user-images.githubusercontent.com/1548104/205973282-12fae1da-1f5e-4854-b96f-00a358dc6766.png)

**Comment by vedantnn71** [comment]
Hey Jakub, thanks for giving it a shot, but it's not launched yet, it's under development.

So if you want to try it, you can build it on your machine rn.

Later on when we release it for production you can try the cloud hosted one or self host it.
